POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username":"nacas3",
    "email": "nacas3@gmail.com",
    "password": "admin123",
    "repit_password": "admin123"
}


###


POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email":"nacas3@gmail.com",
    "password": "admin123"


}