POST http://localhost:3000/api/usuario-perfil/register
Content-Type: application/json

{
    "username":"mr6",
    "nombre": "Mariano",
    "apellidos": "Casilda González",
    "email": "mr@gmail.com",
    "password": "admin123",
    "fecha_nacimiento": "1988-05-10"
    
}



###


POST http://localhost:3000/api/usuario-perfil/login
Content-Type: application/json

{
    "email":"jaime@gmail.com",
    "password": "admin123"

}



###


POST http://localhost:3000/api/photographer-perfil/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjksImV4cGlyZWRBdCI6MTYzOTkzMzE1MywiaWF0IjoxNjM5NTAxMTUzfQ.AyAdselkRRhhfr3sDUeCVuooV3xw_HyMcgYxHQn0KCA


{
    "ubication": "Sevilla",
    "web": "jaime_photo",
    "description":"Fotógrafo profesional"
    
}


###

GET http://localhost:3000/api/photographer-perfil/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjMsImV4cGlyZWRBdCI6MTYzOTkwNTIzMCwiaWF0IjoxNjM5NDczMjMwfQ.mfu61Ezp4kFP3vI9sAPWAW9RaW2HR4cfWX6lgq41Osg



###


PUT http://localhost:3000/api/usuario-perfil/2
Content-Type: application/json

{
    "nombre":"Natalia",
    "apellidos":"Borja",
    "email":"borjis@gmail.com",
    "password":"admin123"

}



###


GET http://localhost:3000/api/usuario-perfil/3
Content-Type: application/json

